### ISSUE TITLE
Modify previous tunnel integration to accomodate new solution

### ISSUE THREAD

**Issue by arcturus** [fxbox/foxbox#177]
In our latest investigation we managed to get the tunnel working with pagekite software.

We can reuse the previous integration with ngrok and adapt for this new software.

**Comment by arcturus** [comment]
I think @ferjm is already working on this

**Comment by ferjm** [comment]
Yes, I am working on this.

We decided to move from ngrok to [pagekite](https://pagekite.net/) because of the lack of SNI support of the former.

The biggest challenge now is authentication. pagekite (and also ngrok) requires a user (domain name) and a shared secret to be able to connect a backend service (foxbox) with a frontend kite (bridge). For demo purposes we can start by having a secret common to all boxes, but in the end we will need a secret per box. Unfortunately pagekite [does not provide a way to add a new domain/secret pair while the bridge is running](https://pagekite.net/wiki/Forum/Jan2012/134cc18abf6/), but it provides the possibility to [delegate the authentication to a dynamic DNS server](http://pagekite.net/wiki/Howto/DnsBasedAuthentication). We are already building a [DNS server](https://github.com/fxbox/dns-server), so we can extend it with the authentication part.

For the first iteration I will just use a common secret for all boxes.

**Comment by ferjm** [comment]
This was closed by #179
